name: selfdriving
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
    - pytorch
dependencies:
    - python>=3.5.2
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - cv2
    - eventlet
    - flask-socketio
    - pytorch=1.0.0
    - tensorboard
    - tensorboardX
    - pandas
    - imageio
    - pyqt=4.11.4
    - pip
    - pip:
        - torch==1.0.0
        - torchvision==0.1.9
        - moviepy
        - opencv-python
        - requests